type User {
	id: Int
	login: String
	avatar_url: String
	tasks: [Task]
	token: String
}

input UserInput {
	login: String
	avatar_url: String
}

type Query {
	users: [User]!
	user(login: String): User!
}

type Mutation {
 	createUser(login: String): User!
 	updateUser(login: String, data: UserInput): User!
 	deleteUser(login: String): User!
}